[project]
name = "codeexplorer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.51.0",
    "ibm-watsonx-ai>=1.3.13",
    "ollama>=0.4.8",
    "openai>=1.78.1",
    "rich>=14.0.0",
]
